language: python
sudo: false
python:
  - "3.7"
  - "3.8"
  - "3.9"
install: pip install tox-travis pep8 coverage
script: tox
before_script: pep8 --ignore=E501,E225 password_policies
after_success: coveralls
